import React from 'react'
import styled from 'styled-components'
import Searchbar from '../components/Searchbar/Searchbar'
import ImageCards from '../components/Cards/ImageCards'

const Container = styled.div`
    height: 100%;
    overflow-y : scroll;
    background: ${({ theme }) => theme.bg};
    padding: 30px 30px;
    padding-bottom: 50px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 20px;
    @media only screen and (max-width: 600px) {
        padding: 6px 10px;
    }  
`

const Headline = styled.h1`
    font-size: 40px;
    font-weight: 700;
    text-align: center;
    display: flex;
    flex-direction: column;
    color: ${({ theme }) => theme.text_primary};
    @media only screen and (max-width: 600px) {
        font-size: 25px;
        padding-left: 10px;
        padding-right: 10px;
    }
`

const Span = styled.span`
    font-size: 20px;
    font-weight: 600;
    color: ${({ theme }) => theme.secondary};
    @media only screen and (max-width: 600px) {
        font-size: 20px;
    }
`

const Wrapper = styled.div`
    display: flex;
    justify-content: center;
    width: 100%;
    max-width: 1100px;
    padding: 32px 0; 
`

const CardWrapper = styled.div`
    display: grid;
    gap: 20px;
    @media (min-width: 1200px) {
    grid-template-columns: repeat(4, 1fr);
  }
    @media(min-width:640px) and (max-width: 1199px) {
        grid-template-columns: repeat(3, 1fr);
    }
    @media (max-width: 689px) {
        grid-template-columns: repeat(2, 1fr);
    }
`

function Home() {
  const item ={
    photo:"https://imgs.search.brave.com/ryrzmK3gV5Zn2LY8Y98D4LXsgyMJovADDghq-XfK2hg/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTU3/NzI3NzI0L3Bob3Rv/L3N1bnNldC5qcGc_/cz02MTJ4NjEyJnc9/MCZrPTIwJmM9Mloy/TVFQWnZYT3FXb3NW/MTRfaVA0NTREbW1j/QVVhT19MRHRoMHBQ/cUt4VT0",
    prompt:"A beautiful sunset",
    author:"John Doe"
  }
  return (
    <Container>
      <Headline>
        Explore popular images in Our community
        <Span>⦿ Generated by AI ⦿</Span>
      </Headline>
      <Searchbar/>
      <Wrapper>
          <CardWrapper>
            <ImageCards item={item}  />
            <ImageCards item={item}  />
            <ImageCards item={item}  />
            <ImageCards item={item}  />
            <ImageCards item={item}  />
          </CardWrapper>
      </Wrapper>
    </Container>
  )
}

export default Home